version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"

  mailcatcher:
    image: zolweb/docker-mailcatcher
    ports:
      - "1080:1080"

  rails:
    depends_on:
      - mysql
      - mailcatcher
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]
    mem_limit: 384m
    extra_hosts:
      - "example.com:127.0.0.1"
      - "baukis.example.com:127.0.0.1"
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    links:
      - "mysql"
